[phases.setup]
nixPkgs = ["...", "php83", "php83Packages.composer", "apacheHttpd", "nodejs", "yarn"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install && npm run build"
]

[phases.build]
cmds = [
  "mkdir -p storage/logs",
  "chmod -R 775 storage",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "heroku-php-apache2 public/"
